version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    environment:
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025' # Web UI
      - '1025:1025' # SMTP
    restart: unless-stopped
